config/routes.rb
Rails.application.routes.draw do
  resources :paintings
  root to: 'paintings#index'
  devise_for :users
  resources :users
  get "v2", :to => "paintings#version2"
end

app/models/painting.rb
class Painting < ActiveRecord::Base
	belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "36x36>", :large => "1000x1000>"  }
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :version2]

  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all.sort { |p1, p2| p2.order <=> p1.order }
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  def version2
    @paintings = Painting.all.sort { |p1, p2| p2.order <=> p1.order }
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:inventory, :title, :medium, :dimension, :year, :exhibition, :current, :image, :order)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def version2
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :root, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
- if user_signed_in?
  %nav.navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Home', root_path, class: 'navbar-brand'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'New Art Work', new_painting_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Haley'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Haley'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}

      = yield

app/views/paintings/_form.html.haml
= simple_form_for(@painting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :inventory
    = f.input :title
    = f.input :medium
    = f.input :dimension
    = f.input :year
    = f.input :exhibition
    = f.input :current
    = f.label :image
    = f.file_field :image, class: "form-control"
    = f.input :order

  .form-actions
    = f.button :submit

app/views/paintings/edit.html.haml
%h1 Editing painting

= render 'form'

= link_to 'Show', @painting
\|
= link_to 'Back', paintings_path
= link_to 'Destroy', @painting, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/paintings/index.html.haml
.hidden-xs
  %table.table.table-responsive
    %tbody
      %thead
        %tr
          %th
          %th Title
          %th
          %th
          %th
          %th 
          %th Year
          - if user_signed_in?
            %th
      - @paintings.each do |painting|
        %tr
          %td{:style => "font-size:.9em;border-top-color:#fff"}= link_to (image_tag painting.image.url(:thumb)), painting

          %td{:style => "font-size:.9em;border-top-color:#fff"}= link_to "#{painting.title}", painting
          %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.inventory
          %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.medium
          %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.dimension
          %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.exhibition
          %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.year
          - if user_signed_in?
            %td{:style => "font-size:.9em;border-top-color:#fff"}= painting.current
.visible-xs          
  - @paintings.each do |painting|
    .row{:style => "padding-top:20px;"}
      .col-xs-2
        = link_to (image_tag painting.image.url(:medium)), painting, :class => "img-responsive"
      .col-xs-10{:style => "padding-top:10px;"}
        %p{:style => "font-size:.9em;"}= link_to "#{painting.title}", painting
        %p{:style => "font-size:.9em;"}= painting.year

app/views/paintings/new.html.haml
%h1 New painting

= render 'form'

= link_to 'Back', paintings_path

app/views/paintings/show.html.haml
.container
  .row
    .col-xs-12
      = link_to "Home", root_path, :class => "btn btn-default btn-large" , :style => "margin-left:12px; width:100px;"
  .row{:style => "padding-top:30px;"}
    .col-sm-9

      = image_tag @painting.image.url(:large), :class => "image-responsive"
    .col-sm-3
      %p{:style => "font-size:.9em;"}
        %b Inventory:
        = @painting.inventory
      %p{:style => "font-size:.9em;"}
        %b Title:
        = @painting.title
      %p{:style => "font-size:.9em;"}
        %b Medium:
        = @painting.medium
      %p{:style => "font-size:.9em;"}
        %b Dimension:
        = @painting.dimension
      %p{:style => "font-size:.9em;"}
        %b Year:
        = @painting.year
      %p{:style => "font-size:.9em;"}
        %b Exhibition:
        = @painting.exhibition
      - if user_signed_in?
        %p
          %b Current:
          = @painting.current
        = link_to 'Edit', edit_painting_path(@painting)
        \|
        = link_to 'Back', paintings_path

app/views/paintings/version2.html.haml
.container
	.row

		- @paintings.each do |painting|
			.col-xs-2
				.div{:style => "height:140px;"}
					= link_to (image_tag painting.image.url(:medium)), painting

				.div{:style => "text-align:center"}= link_to "#{painting.title}", painting
				.div{:style => "text-align:center;font-size:.7em;"}= painting.year

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>